language: c

before_install:
  - sudo apt-get -y install build-essential libopendbx1-dev libopendbx1-sqlite3
  - git submodule add https://github.com/Theintercooler/libuv.git libraries/uv

script:
  - (mkdir cmakebuild && cd cmakebuild && cmake -DHAVE_LOCAL_LIBUV=1 .. && make -j5 && cd .. && rm -rf cmakebuild)

compiler:
  - clang
  - gcc

notifications:
  webhooks: http://n.tkte.ch/h/2600/oVvIcz0cGUV3aC7_Cw2Z2Q4x